from django.contrib.auth.views import LogoutView
from django.urls import path, re_path

from . import views

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    re_path(
        r"^login/(?P<encoded_next>.+)$",
        views.malformed_login_redirect,
        name="malformed_login_redirect",
    ),
    path("login/", views.SmartLoginView.as_view(), name="login"),
    path("register-owner/", views.owner_register, name="owner_register"),
    path("logout/", LogoutView.as_view(next_page="login"), name="logout"),
    path("records/new/", views.daily_record_create, name="daily_record_create"),
    path("flocks/", views.flock_list, name="flock_list"),
    path("flocks/new/", views.flock_create, name="flock_create"),
    path("flocks/<int:flock_id>/edit/", views.flock_update, name="flock_update"),
    path("houses/", views.poultry_house_list, name="poultry_house_list"),
    path("houses/new/", views.poultry_house_create, name="poultry_house_create"),
    path("houses/<int:house_id>/edit/", views.poultry_house_update, name="poultry_house_update"),
    path("feed-types/", views.feed_type_list, name="feed_type_list"),
    path("feed-types/new/", views.feed_type_create, name="feed_type_create"),
    path("feed-types/<int:feed_type_id>/edit/", views.feed_type_update, name="feed_type_update"),
    path("feed-expenses/", views.feed_expense_list, name="feed_expense_list"),
    path("feed-expenses/new/", views.feed_expense_create, name="feed_expense_create"),
    path("feed-expenses/<int:expense_id>/edit/", views.feed_expense_update, name="feed_expense_update"),
    path("feed-expenses/<int:expense_id>/delete/", views.feed_expense_delete, name="feed_expense_delete"),
    path("feed-expenses/export.pdf", views.feed_expenses_export_pdf, name="feed_expenses_export_pdf"),
    path("feed-expenses/export.xlsx", views.feed_expenses_export_excel, name="feed_expenses_export_excel"),
    path("incident-causes/", views.incident_cause_list, name="incident_cause_list"),
    path("incident-causes/new/", views.incident_cause_create, name="incident_cause_create"),
    path("sales/", views.sales_list, name="sales_list"),
    path("sales/new/", views.sale_create, name="sale_create"),
    path("sales/<int:sale_id>/status/", views.sale_status_update, name="sale_status_update"),
    path("sales/export.pdf", views.sales_export_pdf, name="sales_export_pdf"),
    path("customers/", views.customer_list, name="customer_list"),
    path("customers/new/", views.customer_create, name="customer_create"),
    path("customers/<int:customer_id>/edit/", views.customer_update, name="customer_update"),
    path("kpi/", views.kpi_dashboard, name="kpi_dashboard"),
    path("kpi/export.pdf", views.kpi_export_pdf, name="kpi_export_pdf"),
    path("egg-dashboard/", views.egg_dashboard, name="egg_dashboard"),
    path("egg-standards/new/", views.egg_standard_create, name="egg_standard_create"),
    path("egg-standards/<int:standard_id>/edit/", views.egg_standard_update, name="egg_standard_update"),
    path("capa/export.pdf", views.capa_export_pdf, name="capa_export_pdf"),
    path("warehouse/", views.warehouse_operations, name="warehouse_operations"),
    path("warehouse/settings/", views.auto_feed_settings, name="auto_feed_settings"),
    path("automation/settings/", views.automation_settings, name="automation_settings"),
    path("warehouse/ration-phases/new/", views.ration_phase_create, name="ration_phase_create"),
    path("warehouse/ration-phases/<int:phase_id>/edit/", views.ration_phase_update, name="ration_phase_update"),
    path("warehouse/export.xlsx", views.warehouse_export_excel, name="warehouse_export_excel"),
    path("purchase-receipt/", views.purchase_receipt, name="purchase_receipt"),
    path("incidents/", views.incidents_list, name="incidents_list"),
    path("incidents/<int:incident_id>/export.pdf", views.incident_export_pdf, name="incident_export_pdf"),
    path(
        "incidents/<int:incident_id>/overdue-notice.pdf",
        views.incident_overdue_notice_pdf,
        name="incident_overdue_notice_pdf",
    ),
    path("incidents/<int:incident_id>/status/", views.incident_status_update, name="incident_status_update"),
    path("incidents/<int:incident_id>/capa/", views.incident_capa_update, name="incident_capa_update"),
    path("incidents/export.pdf", views.incidents_export_pdf, name="incidents_export_pdf"),
    path("incidents/print/", views.incidents_print, name="incidents_print"),
    path("purchase-requests/", views.purchase_request_list, name="purchase_request_list"),
    path("purchase-requests/new/", views.purchase_request_create, name="purchase_request_create"),
    path(
        "purchase-requests/<int:request_id>/<str:decision>/",
        views.purchase_request_decision,
        name="purchase_request_decision",
    ),
    path(
        "purchase-requests/export.pdf",
        views.purchase_requests_export_pdf,
        name="purchase_requests_export_pdf",
    ),
    path(
        "purchase-requests/print/",
        views.purchase_requests_print,
        name="purchase_requests_print",
    ),
    path("reports/weekly.pdf", views.weekly_report_pdf, name="weekly_report_pdf"),
    path("seed-reference-data/", views.seed_reference_data_view, name="seed_reference_data"),
    path("setup/", views.setup_wizard, {"step": 1}, name="setup_wizard_root"),
    path("setup/<int:step>/", views.setup_wizard, name="setup_wizard"),
    path("managers/", views.manager_list, name="manager_list"),
    path("managers/new/", views.manager_create, name="manager_create"),
    path("managers/<int:user_id>/edit/", views.manager_update, name="manager_update"),
]
