# Generated by Django 4.2.30 on 2026-05-07 15:58

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EggPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('c0', 'C0'), ('c1', 'C1'), ('c2', 'C2')], max_length=8, unique=True)),
                ('price_per_egg', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ('category',),
            },
        ),
        migrations.CreateModel(
            name='FeedType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('cost_per_kg', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Flock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('cross_name', models.CharField(max_length=64)),
                ('placement_date', models.DateField()),
                ('initial_population', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-is_active', 'name'),
            },
        ),
        migrations.CreateModel(
            name='RationPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cross_name', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('start_week', models.PositiveIntegerField()),
                ('end_week', models.PositiveIntegerField()),
                ('daily_consumption_g', models.DecimalField(decimal_places=2, max_digits=8)),
                ('feed_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ration_phases', to='smartpoultry.feedtype')),
            ],
            options={
                'ordering': ('cross_name', 'start_week'),
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_kg', models.DecimalField(decimal_places=3, max_digits=12)),
                ('days_to_zero', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('pending', 'Pending Confirmation'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('feed_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requests', to='smartpoultry.feedtype')),
                ('flock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requests', to='smartpoultry.flock')),
            ],
            options={
                'ordering': ('status', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='FeedStockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('in', 'In'), ('out', 'Out'), ('adjust', 'Adjust')], max_length=16)),
                ('quantity_kg', models.DecimalField(decimal_places=3, max_digits=12)),
                ('movement_date', models.DateField(default=django.utils.timezone.localdate)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('feed_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='smartpoultry.feedtype')),
                ('flock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_movements', to='smartpoultry.flock')),
            ],
            options={
                'ordering': ('-movement_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='FeedStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_kg', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12)),
                ('feed_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='smartpoultry.feedtype')),
            ],
            options={
                'ordering': ('feed_type__name',),
            },
        ),
        migrations.CreateModel(
            name='EggProductionStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cross_name', models.CharField(max_length=64)),
                ('week_number', models.PositiveIntegerField()),
                ('target_efficiency_percent', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'ordering': ('cross_name', 'week_number'),
                'unique_together': {('cross_name', 'week_number')},
            },
        ),
        migrations.CreateModel(
            name='DailyProductionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_date', models.DateField(default=django.utils.timezone.localdate)),
                ('c0_count', models.PositiveIntegerField(default=0)),
                ('c1_count', models.PositiveIntegerField(default=0)),
                ('c2_count', models.PositiveIntegerField(default=0)),
                ('broken_count', models.PositiveIntegerField(default=0)),
                ('chipped_count', models.PositiveIntegerField(default=0)),
                ('mortality_count', models.PositiveIntegerField(default=0)),
                ('live_population_snapshot', models.PositiveIntegerField(default=0, editable=False)),
                ('efficiency_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=6)),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_records', to='smartpoultry.flock')),
            ],
            options={
                'ordering': ('-record_date',),
                'unique_together': {('flock', 'record_date')},
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert_type', models.CharField(choices=[('egg_drop', 'Egg Drop'), ('breakage', 'Breakage'), ('feed_stock', 'Feed Stock')], max_length=32)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], max_length=16)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('flock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='smartpoultry.flock')),
                ('related_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='smartpoultry.dailyproductionrecord')),
            ],
            options={
                'ordering': ('status', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='DailyFinanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('snapshot_date', models.DateField(default=django.utils.timezone.localdate)),
                ('revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('feed_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('gross_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_snapshots', to='smartpoultry.flock')),
            ],
            options={
                'ordering': ('-snapshot_date',),
                'unique_together': {('flock', 'snapshot_date')},
            },
        ),
    ]
