# Generated by Django 4.2.30 on 2026-05-07 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartpoultry', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flock',
            options={'ordering': ('-is_active', 'name'), 'permissions': (('view_dashboard', 'Can view operational dashboard'), ('generate_report', 'Can generate PDF reports'))},
        ),
        migrations.AlterModelOptions(
            name='purchaserequest',
            options={'ordering': ('status', '-created_at'), 'permissions': (('approve_purchaserequest', 'Can approve purchase request'),)},
        ),
    ]
