# Generated by Django 4.2.30 on 2026-05-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartpoultry', '0002_alter_alert_options_alter_flock_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flock',
            options={'ordering': ('-is_active', 'name'), 'permissions': (('view_dashboard', 'Может просматривать дашборд'), ('generate_report', 'Может генерировать PDF-отчеты'))},
        ),
        migrations.AlterModelOptions(
            name='purchaserequest',
            options={'ordering': ('status', '-created_at'), 'permissions': (('approve_purchaserequest', 'Может подтверждать заявку на закупку'),)},
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('egg_drop', 'Падение яйценоскости'), ('breakage', 'Повышенный бой'), ('feed_stock', 'Низкий остаток корма')], max_length=32),
        ),
        migrations.AlterField(
            model_name='alert',
            name='severity',
            field=models.CharField(choices=[('info', 'Инфо'), ('warning', 'Предупреждение'), ('critical', 'Критично')], max_length=16),
        ),
        migrations.AlterField(
            model_name='alert',
            name='status',
            field=models.CharField(choices=[('open', 'Открыт'), ('resolved', 'Решен')], default='open', max_length=16),
        ),
        migrations.AlterField(
            model_name='feedstockmovement',
            name='movement_type',
            field=models.CharField(choices=[('in', 'Приход'), ('out', 'Списание'), ('adjust', 'Корректировка')], max_length=16),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('approved', 'Утверждена'), ('rejected', 'Отклонена')], default='pending', max_length=16),
        ),
    ]
