# Generated by Django 4.2.30 on 2026-05-07 16:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartpoultry', '0003_alter_flock_options_alter_purchaserequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='received_kg',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('approved', 'Утверждена'), ('fulfilled', 'Исполнена'), ('rejected', 'Отклонена')], default='pending', max_length=16),
        ),
    ]
