# Generated by Django 4.2.30 on 2026-05-07 17:29

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smartpoultry', '0005_customer_incidentcause_poultryhouse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedtype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='poultryhouse',
            name='responsible_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_houses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FeedExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expense_date', models.DateField(default=django.utils.timezone.localdate)),
                ('expense_type', models.CharField(choices=[('feed_purchase', 'Закупка корма'), ('transport', 'Доставка/логистика'), ('supplement', 'Добавки/премиксы'), ('other', 'Прочее')], max_length=32)),
                ('quantity_kg', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('feed_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_expenses', to='smartpoultry.feedtype')),
                ('flock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_expenses', to='smartpoultry.flock')),
                ('house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_expenses', to='smartpoultry.poultryhouse')),
            ],
            options={
                'ordering': ('-expense_date', '-created_at'),
            },
        ),
    ]
