# Generated by Django 4.2.30 on 2026-05-08 14:59

from decimal import Decimal
from django.db import migrations, models


def remap_sale_statuses(apps, schema_editor):
    Sale = apps.get_model("smartpoultry", "Sale")
    Sale.objects.filter(status="draft").update(status="new")
    Sale.objects.filter(status="confirmed").update(status="in_progress")
    Sale.objects.filter(status="paid").update(status="completed")


class Migration(migrations.Migration):

    dependencies = [
        ('smartpoultry', '0006_feedtype_is_active_poultryhouse_responsible_manager_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedAutomationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
                ('low_stock_days_threshold', models.DecimalField(decimal_places=2, default=Decimal('7.00'), max_digits=6)),
            ],
            options={
                'verbose_name': 'Настройки автосписания',
                'verbose_name_plural': 'Настройки автосписания',
            },
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('partial_paid', 'Частично оплачена'), ('completed', 'Завершена'), ('canceled', 'Отменена')], default='new', max_length=16),
        ),
        migrations.RunPython(remap_sale_statuses, migrations.RunPython.noop),
    ]
