# Generated by Django 4.2.30 on 2026-05-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartpoultry', '0007_feedautomationsettings_alter_sale_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('egg_drop', 'Падение яйценоскости'), ('breakage', 'Повышенный бой'), ('feed_stock', 'Низкий остаток корма'), ('production_anomaly', 'Производственная аномалия'), ('flock_rotation', 'Плановая замена стада'), ('receivable_overdue', 'Просроченная дебиторка')], max_length=32),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('partial_paid', 'Частично оплачена'), ('overdue', 'Просрочка'), ('completed', 'Завершена'), ('canceled', 'Отменена')], default='new', max_length=16),
        ),
    ]
