# Generated by Django 4.2.30 on 2026-05-08 16:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartpoultry', '0008_alter_alert_alert_type_alter_sale_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('egg_drop_threshold_pct', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5)),
                ('breakage_threshold_pct', models.DecimalField(decimal_places=2, default=Decimal('3.00'), max_digits=5)),
                ('anomaly_egg_drop_threshold_pct', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5)),
                ('anomaly_mortality_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.50'), max_digits=5)),
                ('anomaly_mortality_rate_threshold_pct', models.DecimalField(decimal_places=2, default=Decimal('0.50'), max_digits=5)),
                ('rotation_forecast_days', models.PositiveIntegerField(default=14)),
                ('rotation_min_history_days', models.PositiveIntegerField(default=5)),
                ('rotation_negative_margin_threshold', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('receivable_overdue_days', models.PositiveIntegerField(default=7)),
            ],
            options={
                'verbose_name': 'Настройки автоматизации',
                'verbose_name_plural': 'Настройки автоматизации',
            },
        ),
    ]
