# Generated by Django 4.2.30 on 2026-05-08 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartpoultry', '0009_automationsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='related_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='smartpoultry.sale'),
        ),
    ]
