import { ProcessComponent } from '@features/scheme-editor/components/process-component/ProcessComponent';

export const testComponents = [
	new ProcessComponent({
		id: 100,
		wx: 0,
		wy: 0,
		width: 4,
		height: 2,
		process: {
			id: 1,
			name: 'Process 1',
			description: '',
			parentId: null,
			employeeId: null,
			createdAt: new Date,
			updatedAt: new Date,
			employee: null,
			tasks: [],
		},
	}),
	new ProcessComponent({
		wx: 6,
		wy: 6,
		width: 4,
		height: 2,
		process: {
			id: 1,
			name: 'Process 2',
			description: '',
			parentId: null,
			employeeId: null,
			createdAt: new Date,
			updatedAt: new Date,
			employee: null,
			tasks: [],
		},
		id: 101,
	}),
	new ProcessComponent({
		wx: 10,
		wy: 10,
		width: 4,
		height: 2,
		process: {
			id: 1,
			name: 'Process 3',
			description: '',
			parentId: null,
			employeeId: null,
			createdAt: new Date,
			updatedAt: new Date,
			employee: null,
			tasks: [],
		},
		id: 101,
	}),

	// new RectComponent({
	// 	id: 2,
	// 	title: 'Блок 2',
	// 	x: 10,
	// 	y: 2,
	// 	width: 5,
	// 	height: 3,
	// 	color: '#000000',
	// 	fill: '#ffffff',
	// 	strokeColor: '#0084ff',
	// 	strokeWidth: 2,
	// }),
];
